/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PDV_Final;

import PDV.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LucasSilvaGarcia
 */
public class Compra_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Pessoas_Interface
     */
    public Compra_Interface() {
        initComponents();
        Valor_txt.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valor_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        OpcaoPagamento_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        finalizar_txt = new javax.swing.JButton();
        button_adicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Valor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valor_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor ");

        OpcaoPagamento_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoPagamento_txtActionPerformed(evt);
            }
        });

        jLabel3.setText("Opção Pagamento");

        finalizar_txt.setText("Finalizar Compra");
        finalizar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar_txtActionPerformed(evt);
            }
        });

        button_adicionar.setText("Adicionar Produto");
        button_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_adicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_adicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 540, Short.MAX_VALUE)
                        .addComponent(finalizar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Valor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OpcaoPagamento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpcaoPagamento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizar_txt)
                    .addComponent(button_adicionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Valor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valor_txtActionPerformed
        // TODO add your handling code here:
        try {

        } catch (Exception e) {

        } finally {

        }
    }//GEN-LAST:event_Valor_txtActionPerformed

    private void OpcaoPagamento_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoPagamento_txtActionPerformed
        // TODO add your handling code here:
        try {

        } catch (Exception e) {

        } finally {

        }
    }//GEN-LAST:event_OpcaoPagamento_txtActionPerformed

    private void button_adicionarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {

            String driverName = "com.mysql.jdbc.Driver";

            try {
                Class.forName(driverName);
            } catch (ClassNotFoundException ex) {

            }

// Configurando a nossa conexão com um banco de dados//
            String serverName = "193.123.108.138";    //caminho do servidor do BD

            String mydatabase = "prob2022_2";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "prob2022_2";        //nome de um usuário de seu BD      

            String password = "prob2022_2";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();

//ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
// String nome = "Lianderson ";
            int id = Integer.parseInt(JOptionPane.showInputDialog("Insira Id Produto"));
            String query = "SELECT * FROM lucasgarcia_produtos WHERE id = '" + id + "'";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                //System.out.println("Entrou!");

                //System.out.println(id);
                int valor_produto = Integer.parseInt(rs.getString("Preco"));

                //System.out.println(valor_produto);
                int valor_parcial;
                valor_parcial = Integer.parseInt(Valor_txt.getText());
                valor_parcial = valor_parcial + valor_produto;

                //System.out.println(valor_parcial);
                Valor_txt.setText(String.valueOf(valor_parcial));
                
                JOptionPane.showMessageDialog(null,"Produto Adicionado");

            }
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());

        } // TODO add your handling code here: }                                        
    }

    private void finalizar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar_txtActionPerformed
        // TODO add your handling code here:
        try {

            String driverName = "com.mysql.jdbc.Driver";
            try {
                Class.forName(driverName);
            } catch (ClassNotFoundException ex) {

            }

// Configurando a nossa conexão com um banco de dados//
            String serverName = "193.123.108.138";    //caminho do servidor do BD

            String mydatabase = "prob2022_2";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "prob2022_2";        //nome de um usuário de seu BD      

            String password = "prob2022_2";      //sua senha de acesso

            Connection conn = DriverManager.getConnection(url, username, password);

            Statement stmt = conn.createStatement();

            stmt.execute("INSERT INTO lucasgarcia_compra(Valor,OpcaoPagamento) VALUES ('"+Valor_txt.getText()+"','"+OpcaoPagamento_txt.getText()+"')");
            conn.close();
            JOptionPane.showMessageDialog(null, "Finalizado com Sucesso!");
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());

        }


    }//GEN-LAST:event_finalizar_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra_Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra_Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra_Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra_Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OpcaoPagamento_txt;
    private javax.swing.JTextField Valor_txt;
    private javax.swing.JButton button_adicionar;
    private javax.swing.JButton finalizar_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
